### ISSUE TITLE
Wrong icon size being installed

### ISSUE THREAD

**Issue by AsciiWolf** [flathub/org.zdoom.GZDoom#1]
Same issue as flathub/com.zandronum.Zandronum/issues/2.

**Comment by Eonfge** [comment]
Yeah, was already aware of that. I'll also address the screenshot issue that bilel mentioned.

**Comment by Eonfge** [comment]
Fixed this and the screenshots issue. Thanks for paying attention, with the build server being offline over the weekend, I had not noticed that both went live
