### ISSUE TITLE
Fails to run with error "sh: kdialog: command not found"

### ISSUE THREAD

**Issue by uncivilgentleman** [flathub/org.zdoom.GZDoom#10]
The Flatpak fails to run on Opensuse Tumbleweed giving this output.

```
user@computer:~> flatpak run org.zdoom.GZDoom
GZDoom g4.3.3-m - 2020-01-20 22:20:34 +0100 - SDL version
Compiled on Jan 21 2020

M_LoadDefaults: Load system defaults.
sh: kdialog: command not found
```
If you need any additional information just let me know.

**Comment by Eonfge** [comment]
Weird question perhaps; Can you try it using the application launcher (desktop shortcut)?

What I think, is that GZDoom wants to show you a dialog message but it cant connect to a display.

**Comment by uncivilgentleman** [comment]
It fails with no error message.
https://imgur.com/a/hUD2KjI

**Comment by Eonfge** [comment]
Could you give me a readout of your hardware specs, like with `inxi -Fxxx`?

Also, do you have any experience using a debugger? I might be able to help you get more info, but it will be a bit more technical.

**Comment by Eonfge** [comment]
Good news. I've reproduced the issue.

### Stacktrace

```
[📦 org.zdoom.GZDoom ~]$ gdb /app/bin/gzdoom
GNU gdb (GDB) 8.3.1
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-unknown-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /app/bin/gzdoom...
Reading symbols from /usr/lib/debug//app/bin/gzdoom.debug...
con(gdb) continue
The program is not being run.
(gdb) start
Temporary breakpoint 1 at 0x270330: main. (2 locations)
Starting program: /app/bin/gzdoom 
warning: File "/usr/lib/x86_64-linux-gnu/libthread_db-1.0.so" auto-loading has been declined by your `auto-load safe-path' set to "$debugdir:$datadir/auto-load".
To enable execution of this file add
        add-auto-load-safe-path /usr/lib/x86_64-linux-gnu/libthread_db-1.0.so
line to your configuration file "/home/kevin/.gdbinit".
To completely disable this security protection add
        set auto-load safe-path /
line to your configuration file "/home/kevin/.gdbinit".
For more information about this security protection see the
"Auto-loading safe path" section in the GDB manual.  E.g., run from the shell:
        info "(gdb)Auto-loading safe path"
warning: Unable to find libthread_db matching inferior's thread library, thread debugging will not be available.
[New LWP 9]

Thread 1 "gzdoom" hit Temporary breakpoint 1, main (argc=1, argv=0x7fffffffdb88) at src/posix/sdl/i_main.cpp:160
160     {
(gdb) continue
Continuing.
GZDoom g4.3.3-m - 2020-01-20 22:20:34 +0100 - SDL version
Compiled on Jan 21 2020

Thread 2 "gzdoom" received signal SIG33, Real-time event 33.
[Switching to LWP 9]
0x00007ffff78f9d05 in pthread_cond_wait () from /usr/lib/x86_64-linux-gnu/libpthread.so.0
(gdb) continue
Continuing.

M_LoadDefaults: Load system defaults.
[Detaching after vfork from child process 10]
[LWP 9 exited]
[Inferior 1 (process 5) exited with code 0377]
(gdb) sh: kdialog: command not found
```

**Comment by Eonfge** [comment]
This is a complex issue for which I don't have a straightforward answer at the moment. I think that you could still use GZDoom using the CLI, [some base docs](https://github.com/flathub/org.zdoom.GZDoom/blob/master/README.md), but realistically, this should not have happened.

The problem is the wad file selector at the start. It's supposed to show you a simple menu, but for some reason it can't find kdialog. A simple UI tool akin to Zenity. Why it doesn't work, I don't know, because all libraries that you need should have been bundled.

I'll have to research this topic, and possibly ask the Flatpak people for some more clarity. I'll also see if I can reproduce it on Kubuntu.

**Comment by Eonfge** [comment]
@uncivilgentleman Could you try it out?

```
flatpak install --user https://dl.flathub.org/build-repo/18209/org.zdoom.GZDoom.flatpakref
```

I will have to discusss this upstream, but I do have a possible fix for KDE users. Apparently, there is a gode-path inside the application to deal with KDE users, but that path makes no sense n the context of Flatpak.

**Comment by Eonfge** [comment]
I've published a temporary fix and I discussed the topic upstream, to make this more robust in the future. Thanks for bringing this to my attention. Sad that nobody else reported this, because you'll not be the first person to run into this.
