### ISSUE TITLE
Can't find WADs outside .config/gzdoom

### ISSUE THREAD

**Issue by makeworld-the-better-one** [flathub/org.zdoom.GZDoom#23]
GZDoom only seems to find WADs when they are in `~/.var/app/org.zdoom.GZDoom/.config/gzdoom/`. Even if I run
```
flatpak override org.zdoom.GZDoom --filesystem=/usr/share/games/doom --user
```
and have `/usr/share/games/doom` specified in the `config.ini` file, it will not find those WADs.

**Comment by Eonfge** [comment]
The directory `/usr` is blacklisted. You can't break the sandbox for that directory. Is there any reason that you have these user files in `/usr/share/games/` because they're certainly not part of any distro that I know of.

**Comment by makeworld-the-better-one** [comment]
Thanks for explaining, that makes sense. I don't remember exactly why I put my WADs there.
