### ISSUE TITLE
GZDoom 4.8.0

### ISSUE THREAD

**Issue by Eonfge** [flathub/org.zdoom.GZDoom#39]
There is currently a bug with 4.8.0 that blocks larger adoption: https://github.com/coelckers/gzdoom/issues/1615
There is also an ticket over at shared-modules: https://github.com/flathub/shared-modules/pull/192

**Comment by eliw00d** [comment]
Looks like the bug has been fixed. Any chance of a 4.8.x release in the near future?

**Comment by Eonfge** [comment]
You send my on a wild goose chase. I thought that they finally released the fix... but they didn't. 4.8.2 is made after people patched this issue and there is no new release yet.

I will patch it manually, so that the release can go through, but I would ask you to also poke GZDoom's team for a new release.

**Comment by eliw00d** [comment]
You're right, a new release wasn't created that included that commit. I'll post over there to see about a 4.8.3. Sorry about that!

**Comment by Eonfge** [comment]
Fear not. I patched it manually. GZDoom 4.8.2 is available on Flathub with this minor patch, and when the next version comes around I'll remove the patch and follow mainline again.

**Comment by eliw00d** [comment]
Awesome, thank you so much! I did ask for a 4.8.3 release [here](https://github.com/ZDoom/gzdoom/issues/1615#issuecomment-1221568967), so hopefully it won't be too long before you can follow mainline again.
