### ISSUE TITLE
GZDoom stays glitched on foreground after exiting the game on Wayland

### ISSUE THREAD

**Issue by AsciiWolf** [flathub/org.zdoom.GZDoom#4]
This is a really weird issue that happens on my Fedora 30 system with GNOME on Wayland and Intel GPU. After exiting the game, the content of its window stays displayed on the foreground although the game process is gone (`flatpak ps` shows nothing). See this screenshot:
![GZDoom glitch](https://user-images.githubusercontent.com/2339930/67197048-48c9be80-f3fc-11e9-922d-b42739ebcead.png)

I have tried changing enabling/disabling `x11`, `fallback-x11` and `wayland` sockets, but nothing changed.

**Comment by rowbawts** [comment]
I have this exact same issue.

OS: Fedora 30 (Workstation Edition) x86_64 
Kernel: 5.3.6-200.fc30.x86_64 
Uptime: 13 hours, 19 mins 
Packages: 1759 (rpm), 66 (flatpak)
Shell: bash 5.0.7
Resolution: 1920x1080
DE: GNOME 3.32.2
Theme: Mojave-dark [GTK2/3]
Icons: Papirus-Dark [GTK2/3]
Terminal: gnome-terminal
CPU: Intel i7-3930K (12) @ 3.800GHz
GPU: AMD ATI Radeon RX 470/480/570/570X/58
Memory: 4382MiB / 15952MiB

**Comment by Eonfge** [comment]
@AsciiWolf and @rowbawts, Can either of your confirm if this issue still happens. I've been doing some digging ever since you mentioned it, but I have little idea what causes it. The problem is worsened by the fact that I don't actually have a device capable of running Wayland.

**Comment by AsciiWolf** [comment]
It seems that the issue does not happen anymore on my Fedora 31 machine. Thanks!
