### ISSUE TITLE
Audio issue, potentially with libmpg123 in latest flatpak release

### ISSUE THREAD

**Issue by andrewschott** [flathub/org.zdoom.GZDoom#45]
Reverting back to 4.7.1 things work fine, but on the latest 4.8.2, midi works fine, but most sound effects such as gunshots, are broken in any external wad.  Local installation rpms do not exhibit this behavior:

```
E1M1 - Hangar

Note: Illegal Audio-MPEG-Header 0x00000000 at offset 10016.==============================================================================================================================================....]
Note: Trying to resync...
Note: Hit end of (available) data during resync.
Note: Illegal Audio-MPEG-Header 0x00000000 at offset 11155.
Note: Trying to resync...
Note: Hit end of (available) data during resync.
Note: Illegal Audio-MPEG-Header 0x00000000 at offset 10762.
Note: Trying to resync...
Note: Hit end of (available) data during resync.
Note: Illegal Audio-MPEG-Header 0x00000000 at offset 12142.
Note: Trying to resync...
Note: Hit end of (available) data during resync.
Note: Illegal Audio-MPEG-Header 0x00000000 at offset 16551.
Note: Trying to resync...
Note: Hit end of (available) data during resync.
Note: Illegal Audio-MPEG-Header 0x00000000 at offset 20061.
Note: Trying to resync...
Note: Hit end of (available) data during resync.
Note: Illegal Audio-MPEG-Header 0x00000000 at offset 17047.
Note: Trying to resync...
Note: Hit end of (available) data during resync.
[../src/libmpg123/parse.c:do_readahead():1081] error: cannot seek!
Note: Illegal Audio-MPEG-Header 0x00000000 at offset 6760.
Note: Trying to resync...
Note: Hit end of (available) data during resync.
Note: Illegal Audio-MPEG-Header 0x00000000 at offset 8548.
Note: Trying to resync...
Note: Hit end of (available) data during resync.
[../src/libmpg123/parse.c:do_readahead():1081] error: cannot seek!
Note: Illegal Audio-MPEG-Header 0x00000000 at offset 9608.
Note: Trying to resync...
Note: Hit end of (available) data during resync.
```

That goes on and on as I play a map.  Initially I suspected the new 4.8 version may have incompatibilities with the pk3s I was adding in, but using the local install rather than the flatpak things work as expected.  When going thru console errors I noticed this.  I wasn't able to determine a permission issue (not saying there isn't, just I couldn't figure one out).

In the end, playing stock wads work fine (ultimate doom, doom2, etc).  Any pk3 I add that modifies any sounds fails hard.  Any remedies on my end I can try?  I would have hoped if this was an actual bug that others would have chimed in by now.

Thanks!

**Comment by Eonfge** [comment]
Are we actually sure that is uses mpg123, because I remember that there is also a `libsndfile` plug-in. Perhaps I should look into the dependencies there who might throw a problem.

Just for reference, can you give name an external wad that has this issue?

**Comment by Eonfge** [comment]
For testing, I quickly made a build with libsndfile included;

https://github.com/flathub/org.zdoom.GZDoom/pull/46

Can you give that one a spin as well?

**Comment by andrewschott** [comment]
Your linked build works perfectly, thanks!  And to anwer your question, I tried a few of the brutal doom mods and a few old and new Obsidian generated wads that all had issues in the released version on flathub, your new one works perfectly again.

Again, thanks for the fix!

**Comment by Eonfge** [comment]
I'll keep the issue open until released. This also casts another light on the other GZDoom related projects that I maintain, since they will all have this problem.

**Comment by Eonfge** [comment]
Closing on behalf of https://github.com/flathub/org.zdoom.GZDoom/issues/47

thanks for your help testing
