### ISSUE TITLE
Crashes due to assertions in build

### ISSUE THREAD

**Issue by cncz42** [flathub/org.zdoom.GZDoom#71]
It seems that the shared-modules for this package uses -DCMAKE_BUILD_TYPE=RelWithDebInfo instead of Release to compile gzdoom, resulting in [crashes like the one that brought this to my attention](https://github.com/ZDoom/gzdoom/issues/2656) due to gcc assertions as well as probable performance downgrade.

**Comment by Eonfge** [comment]
I'll have to check it all first, but this is easy to change;
https://github.com/flathub/shared-modules/pull/308

**Comment by Eonfge** [comment]
Changed the build-type it since upstream recommends building without debug info
